version: "3.8"
networks:
  alsinet:
    external: true
services:
  web:
    build: .
    container_name: flmiguel
    image: master-image
    ports:
      - 1234:5050
    depends_on:
      - "redis"
    environment:
      - flask_port=$FLASKPORT
      - flask_host=$FLASKHOST
      - FLASK_APP=$FLASK_APP
      - DB_URL=$DB_URL
      - REDIS_URL=$REDIS_URL
      - REDIS_PWD=$REDIS_PWD
    volumes:
      - .env:/usr/src/app/flmiguel/.env
      - ./logs:/usr/src/app/flmiguel/logs/
    networks:
      - alsinet

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: es01
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      # - node.name=es01
      # - cluster.name=es-docker-cluster
      # - cluster.initial_master_nodes=es01
      # - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - alsinet

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PWD
    # command: redis-server --save 500 1 --loglevel debug --requirepass $REDIS_PWD
    volumes:
      - cache:/data

  worker:
    image: master-image
    environment:
      - flask_port=$FLASKPORT
      - flask_host=$FLASKHOST
      - FLASK_APP=$FLASK_APP
      - DB_URL=$DB_URL
      - REDIS_URL=$REDIS_URL
      - REDIS_PWD=$REDIS_PWD
    depends_on:
      - redis
    # command: rq worker --name worker --url redis://:8a12d677d0249e172249233b16275f2691425f41@192.168.1.47:6379/0
    command: rq worker -u redis://:8a12d677d0249e172249233b16275f2691425f41@192.168.1.47:6379/0 microblog-tasks

volumes:
  data01:
    driver: local
  cache:
    driver: local